const restaurantData = [
    {
      id: 1,
      name: "Tandoori Nights",
      cuisine: ["Indian", "North Indian", "Tandoor"],
      rating: 4.3,
      deliveryTime: "30 mins",
      costForTwo: "₹400 for two",
      image: "https://blog.swiggy.com/wp-content/uploads/2024/10/Image1_-Tandoori-Chicken-1024x538.jpg",
      address: "MG Road, Delhi",
    },
    {
      id: 2,
      name: "Pizza Planet",
      cuisine: ["Italian", "Pizza", "Fast Food"],
      rating: 4.1,
      deliveryTime: "25 mins",
      costForTwo: "₹600 for two",
      image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg",
      address: "HSR Layout, Bangalore",
    },
    {
      id: 3,
      name: "Sushi Zen",
      cuisine: ["Japanese", "Sushi"],
      rating: 4.6,
      deliveryTime: "45 mins",
      costForTwo: "₹1200 for two",
      image: "https://images.contentstack.io/v3/assets/bltcedd8dbd5891265b/blt6542458a3d1e8c6f/664cbc3d213dc5f7fd48a20e/origin-of-sushi-hero.jpeg?q=70&width=3840&auto=webp",
      address: "Bandra West, Mumbai",
    },
    {
      id: 4,
      name: "Burger Bros",
      cuisine: ["American", "Burgers"],
      rating: 4.0,
      deliveryTime: "20 mins",
      costForTwo: "₹300 for two",
      image: "https://www.foodandwine.com/thmb/DI29Houjc_ccAtFKly0BbVsusHc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/crispy-comte-cheesburgers-FT-RECIPE0921-6166c6552b7148e8a8561f7765ddf20b.jpg  ",
      address: "Kondapur, Hyderabad",
    },
    {
      id: 5,
      name: "Green Bowl",
      cuisine: ["Healthy", "Salads", "Vegan"],
      rating: 4.5,
      deliveryTime: "35 mins",
      costForTwo: "₹500 for two",
      image: "https://images.immediate.co.uk/production/volatile/sites/30/2023/06/GettyImages-1416818056-6ecd1e0.jpg?quality=90&resize=556,505",
      address: "Koregaon Park, Pune",
    },
    {
        id: 6,
        name: "The Curry House",
        cuisine: ["Indian", "South Indian", "Curry"],
        rating: 4.2,
        deliveryTime: "40 mins",
        costForTwo: "₹450 for two",
        image: "https://assets.vogue.com/photos/63d169f727f1d528635b4287/3:2/w_3630,h_2420,c_limit/GettyImages-1292563627.jpg",
        address: "Andheri East, Mumbai",
      },
      {
        id: 7,
        name: "Wok Express",
        cuisine: ["Chinese", "Asian", "Noodles"],
        rating: 4.0,
        deliveryTime: "30 mins",
        costForTwo: "₹350 for two",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrSodh2_bz3T_LLA16yP9WdpyAoAUkC5-TdA&s",
        address: "BTM Layout, Bangalore",
      },
      {
        id: 8,
        name: "French Toast",
        cuisine: ["Cafe", "French", "Breakfast"],
        rating: 4.4,
        deliveryTime: "20 mins",
        costForTwo: "₹550 for two",
        image: "https://thekitchencommunity.org/wp-content/uploads/2022/02/french-breakfast-foods-1-1200x800.jpg",
        address: "Connaught Place, Delhi",
      },
      {
        id: 9,
        name: "Kebab Kingdom",
        cuisine: ["Mughlai", "Kebabs", "Grill"],
        rating: 4.6,
        deliveryTime: "45 mins",
        costForTwo: "₹700 for two",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Lula_kebab_2.jpg",
        address: "Charminar, Hyderabad",
      },
      {
        id: 10,
        name: "Veggie Vibes",
        cuisine: ["Vegetarian", "Salads", "Healthy"],
        rating: 4.3,
        deliveryTime: "25 mins",
        costForTwo: "₹400 for two",
        image: "https://catalog.wlimg.com/1/13591746/other-images/1011524.jpg",
        address: "Sector 62, Noida",
      }
      
  ];

  export default restaurantData